### ISSUE TITLE
Add option for pubDate to respect "Date recorded" field per episode

### ISSUE THREAD

**Issue by thorseye** [TheCraigHewitt/Seriously-Simple-Podcasting#116] opened 2016-07-15 21:19 UTC
If a value is entered in the **Date recorded**, one would think that this should be the value for the podcast item date, but from what I can tell this is not the case. Instead the podcast feed always get the **Published date** as **pubDate**.

Is this intentional or could this be fixed?

**Comment by hlashbrooke** [comment] 2016-07-16 04:52
This is by design - in many (most?) cases the recorded date does not reflect the published date. For example, you record a sermon no a Sunday morning and then you publish the episode on the Monday or Tuesday. Or you record a presentation that will be used as a podcast episode and only publish it a day or two later.

If you want the two dates to match, then you must manually set the published date to be the same as the recorded date.

**Comment by thorseye** [comment] 2016-07-16 08:59
In my case, I'm using the podcast plugins together with an events plugin. I've setup a series of events, which I publish months before the actual event. When the podcast is recorded, I add the mp3 to the event, but the publish date is still months before the actual date of the podcast. Since the feed is not updated until the MP3 file is added, it's quite weird to use the publish date as podcast publish date in this case. 

Is this not a valid use case? My thoughts is that this could be a plugin setting.

**Comment by hlashbrooke** [comment] 2016-07-18 13:08
You're right - that is a valid use case that I hadn't considered before.

So, just to confirm, you're thinking that the `pubDate` in the RSS feed should match **Date recorded** from the episode settings? That makes a lot of sense and I think a good way to handle it would be to add an option to the episode settings where you can optionally set the `pubDate` to natch the **Date recorded**. That would be easy and wouldn't add too much more complexity as it would just be a basic checkbox in the episode settings.

Do you think that would be a logical solution? Would that work for your use case?

**Comment by thorseye** [comment] 2016-07-18 16:19
Yes, that would fit my use case perfectly :)
Thanks for reopening the issue!

**Comment by hlashbrooke** [comment] 2016-07-18 17:42
Cool - I'll look into this and see about including it in the next release :)

**Comment by jonathanbossenger** [comment] 2017-08-28 08:55
Fixed by #205

**Closed by jonathanbossenger** 2017-08-28 08:55 UTC
Labels: enhancement
